apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-quarkus-application
spec:
  params:
  - name: SOURCE_GIT_URL
    type: string
    description: The application git repository url
    default: https://github.com/rh-intelligent-application-practice/mlops-demo-application-gitops.git
  - name: SOURCE_GIT_REVISION
    type: string
    default: master
    description: The application git repository revision

  results:
  - name: image-tag
    description: The Production Image Tag
    value: prod-$(tasks.generate-tag.results.image-tag)

  workspaces:
  - name: app-source

  tasks:
  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source

  - name: generate-tag
    taskRef:
      kind: Task
      name: generate-tag

  - name: update-values
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: update-values
    params:
    - name: fileName
      value: values.yaml
    - name: filePath
      value: environments/dev/charts/iris-inference-service
    - name: directory
      value: app-source
    - name: imageTag
      value: $(tasks.generate-tag.results.image-tag)
    - name: verbose
      value: "true"