apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-values
  annotations:
    tekton.dev/displayName: "Update Values yaml"
spec:
  params:
  - name: directory
    description: the directory to work in
    type: string
  - name: filePath
    description: Path of the file to be updated
    type: string
  - name: fileName
    description: Name of the file to be updated
    type: string
  - name: imageTag
    description: The image tag to be written into the YAML
    type: string
  - name: verbose
    description: Log the commands used during execution
    type: string
    default: "true"
  volumes:
  - name: repository
    emptyDir: {}
  steps:
  - name: update-yaml
    image: ubi8/ubi:8.1
    workingDir: "$(params.directory)"
    # volumeMounts:
    # - name: repository
    #   mountPath: /workspace/repository
    script: |
      #!/usr/bin/env sh
      set -e

      if [[ "$(params.verbose)" == "true" ]] ; then
        echo "**** Updating $(params.fileName) image tag to $(params.imageTag)"
      fi
      
      sed -i "s/tag: ".*"/tag: "$(params.imageTag)"/" ./$(params.filePath)/$(params.fileName)

  # - name: commit-push-changes
  #   image: alpine/git:v2.26.2
  #   workingDir: "/workspace/repository"
  #   volumeMounts:
  #   - name: repository
  #     mountPath: /workspace/repository
  #   script: |
  #     #!/usr/bin/env sh
  #     set -e

  #     git config --global user.email "tekton@tekton.dev"
  #     git config --global user.name "OpenShift Pipeline"
  #     git add .
  #     git commit --allow-empty -m "[OpenShift Pipeline] Updating $(params.fileName) image to $(params.image):$(params.imageTag)"
  #     git push origin "$(params.gitRepositoryRevision)"
